test:opensuse:
  image: drfaustroll/esl:opensuse-tumbleweed
  script:
    - source /etc/profile.d/lmod.sh
    - module load gnu/7  
   # Prepare source tree
    - ./wipeout.sh
    - ./autogen.sh
    - CC=gcc CFLAGS="-O3" ./configure --enable-fortran
    - make -j4
    - make check 



test:debian-debian:
  image: drfaustroll/esl:debian-latest
  script:
    - ./wipeout.sh
    - ./autogen.sh
    - CC=gcc CFLAGS="-O3" ./configure --enable-fortran 
    - make -j4
    - make check 
