dist: trusty
sudo: required

notifications:
    email:
        recipients:
            - devops@materialsevolution.es
        on_failure: always
        on_success: change

branches:
    only:
        - develop
        - master
        - travis

language: c
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gfortran-5
            - autoconf-archive
            - check
            - gsl-bin
            - libgsl0ldbl
            - libgsl0-dbg
            - libgsl0-dev
            - libxml2-dbg
            - libxml2-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && F77=gfortran-5 && FC=gfortran-5"

before_install:
    - eval "${MATRIX_EVAL}"
    - pip install --user cpp-coveralls
    - ./autogen.sh

script:
    - ./configure --enable-gcov && make && make check

after_success:
  - coveralls --gcov-options '\-lp'

