#!/bin/sh

for srcfile in *.c
do
  ( gcov -r $srcfile || gcov $srcfile ) > /dev/null 2> /dev/null
done

if perl -CS ./check-coverage *.gcov
then
  exit 0
else
  grep -E -A3 -B3 '(#####)|(SNH)' *.gcov
  exit 1
fi
