/** subroutine to read in abinit header which is generic to all psp files for abinit */

#include <stdio.h>
#include <pspio.h>
#include <string.h>

     read (tmp_unit, '(a)' )pspheads(ipsp)%title
     read (tmp_unit,*)pspheads(ipsp)%znuclpsp,pspheads(ipsp)%zionpsp,pspheads(ipsp)%pspdat
     read (tmp_unit,*)pspheads(ipsp)%pspcod,pspheads(ipsp)%pspxc,pspheads(ipsp)%lmax,idum,mmax

int read_abinit_header (fname, psp_data){

 /// input variables
  char *fname; /**< file name to be read in */
  psp_data_t psp_data; /**< output: pseudopotential info is partially filled in present routine */

 /// local variables
  FILE* fp;            /**< file pointer for reading in */
  int ierr;
  int ncharead = 1000;
  int pspcod;
  int pspxc; 
  char line[ncharead];

 /// open file
  fp = fopen(fname, "r");
 /// check for fp being null

  /**< read in title */
  getline(&line, &ncharead, fp);
  /// check for line != NULL
  psp_data.title = (*char) malloc (strlen(line));
  psp_data.title = line[0:strlen(line)-1];
 
  /**< read in atomic number, pseudopotential ion charge (= num of valence electrons), and abinit data flag (not used) */
  getline(&line, &ncharead, fp);
  narg = sscanf (line, "%f %f", &psp_data.z, &psp_data.zvalence);
  ///check narg is equal to 2
 
  /**< read in psp code and xc code*/
  getline(&line, &ncharead, fp);
  narg = sscanf (line, "%d %d", &pspcod, &pspxc);
  ///check narg is equal to 2

// copied from abinit web site http://www.abinit.org/documentation/helpfiles/for-v6.8/users/abinit_help.html#5
/*
    pspcod=1 : Troullier-Martins pseudopotentials, generated by DC Allan and A Khein, see ~abinit/doc/psp_infos/psp1_info.txt ;
    pspcod=2 : Goedecker-Teter-Hutter (GTH) pseudopotentials. See Phys. Rev. B 54, 1703 (1996) if needed ;
    pspcod=3 : Hartwigsen-Goedecker-Hutter pseudopotentials. See Phys. Rev. B 58, 3641 (1998) if needed, and the file ~abinit/doc/psp_infos/psp3_info.txt ;
    pspcod=4 or 5 : old format pseudopotentials, see ~abinit/doc/psp_infos/psp45_info.txt ;
       NOTE: 5 is used also for new psp generated with the Martins code, including 2 projectors for spin orbit coupling
    pspcod=6 : pseudopotentials from the fhi98pp code, see ~abinit/doc/psp_infos/psp6_info.txt ;
    pspcod=7 : pseudo atomic data for PAW ;
    pspcod=8 : pseudopotential file format from Don Hamann, providing additional flexibility. 
*/ 
  switch(pspcod){
    case 1:
      psp_data.scheme = TM2;
      break;
    case 2:
      psp_data.scheme = GTH;
      break;
    case 3:
      psp_data.scheme = HGH;
      break;
    default:
///check if we should complain here - not treated in pspio
  }

 /// close file
  ierr = close(fp);
 ///check for ierr being non 0


return 0

}
